version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: pnoker/iot-dc3-web:1.0.0
    restart: always
    ports:
      - 8080:80
      - 443:443
    environment:
      - APP_API_PATH=dc3-gateway
      - APP_API_PORT=8000
    container_name: iot-dc3-web
    hostname: iot-dc3-web
    volumes:
      - nginx:/var/log/nginx
    networks:
      dc3net:
        aliases:
          - iot-dc3-web

volumes:
  nginx:

networks:
  dc3net:
    driver: 'bridge'
...
